### PR TITLE
Support Puppet >= 4.9 & Ruby 2.3.1

### PR DESCRIPTION
**Pull request by Phil-Friderici**
This change also align the testing rig.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
There is still a Ruby 1.8.7 related problem.
My guess here is that rspec-puppet-facts is causing a dependency problem.

It is also failing on a no-change PR https://github.com/emahags/puppet-module-nfsclient/pull/5

@emahags maybe you can find a way to get rspec-puppet-facts working on Ruby 1.8.7 ?

**Comment by marhag87** [comment]
@Phil-Friderici: Sorry, have not really touched puppet in a while. You'll probably find a solution faster than me.

**Comment by Phil-Friderici** [comment]
Could you live without rspec-puppet-facts functionality ?

This is not used in the other modules and I don't want to spent too much time on a one time problem.

**Comment by marhag87** [comment]
Sure, but I guess you'd have to add a lot of data manually instead

**Comment by ghost** [comment]
Due to the fact, that this PR hasn't been merged yet, and another functional PR (https://github.com/gillarkod/puppet-module-nfsclient/pull/6) took priority, and due to permission issues on the repo, and due to Phil being on not available for now, we'll follow-up this work here: https://github.com/kodguru/puppet-module-nfsclient/pull/1

**Pull request closed without merging**
