### PR TITLE
Add variable type and content validations

### PR DESCRIPTION
**Pull request by Phil-Friderici**
- fix dependency issues when $gss or $keytab is set on its own

Found this dependency issue while adding the variable type/content checks.
When only one parameter is set, hard coded dependencies did not match.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
There is a failure in the dependency module nfs. I am working on a fix for that to get the spec tests green again.

**Comment by Phil-Friderici** [comment]
Fix is ready, see https://github.com/ghoneycutt/puppet-module-nfs/pull/70
After this got merged the test should become green again.

**Comment by Phil-Friderici** [comment]
Found and fixed a Suse only related error while testing STRICT_VARIABLES=yes.
I had to explicit set $nfs_requires to undef to fix it codewise only. I don't know if this setting should have a better setting or if it's intenionally left empty. If so, please remove my comment.

**Comment by ghost** [comment]
Didn't get a mail notification for this, odd. Thanks for the contribution!

**Pull request merged**
